### ISSUE TITLE
🔨 make

### ISSUE THREAD

**Issue by unicornware** [flex-development/mkdist#3]
### Prerequisites

- [X] i am a project maintainer

### Proposed work

implementing the main method, `make`.

### Success criteria

- [ ] handle defaults with [`defu`][1]
- [ ] scan and filter input files
- [ ] transform files using the [esbuild build api][2] to allow for esbuild plugin usage
- [ ] write files to output directory
- [ ] log build results

[1]: https://github.com/unjs/defu
[2]: https://esbuild.github.io/api/#build-api

### Related documents

- [`defu`][1]
- [`micromatch`][2]
- [esbuild - Build API][3]

[1]: https://github.com/unjs/defu
[2]: https://github.com/micromatch/micromatch
[3]: https://esbuild.github.io/api/#build-api

### Additional context

N/A

### Linked issues

N/A
